### ISSUE TITLE
Uwagi

### ISSUE THREAD

**Issue by MarcinCiura** [przemekbarczyk/arkanoid#1]
1. Wyrzucić zbędny katalog `.idea` oraz pliki `desktop.ini` i `game_module/desktop.ini`

2. W `game.py`: usunąć wywołanie `pygame.init()` z `Game.__init__()`. Zamiast tego na końcu pliku napisać:
```python
def main():
    pygame.init()
    game = Game()
    game.run()


if __name__ == '__main__':
    main()
```

3. Godne pochwały są docstringi. Jedyne, do czego mogę się przyczepić, to że lepiej, żeby w pierwszym wierszu podawały zwięzły opis (poniżej 80 znaków), a ewentualnie po pustym wierszu jego dopowiedzenie ([punkt 3.8.1](https://google.github.io/styleguide/pyguide.html#381-docstrings)). Nadto nie należy zakładać, że czytelnik rozumie te same skróty, co my ([punkt 3.16](https://google.github.io/styleguide/pyguide.html#316-naming)). Czyli po poprawkach np. tak:
```python
    """Klasa zawierająca przyciski z menu.

    Gracz może wybrać przycisk, przemieszczając kursor myszy
    na jego pole i klikając lewym przyciskiem myszy.
    """
```

4. Drobiazg: np. w `block.py` zamiast komentarzy z `...` na końcu lepiej napisać ten komentarz w całości w wierszu powyżej.

5. Stałe w stylu `(255, 255, 255)` (ta jest z `buttons.py`) przenieść do `constants.py`

6. W `Judge.__init__()` usunąć wywołanie `pygame.font.init()` — przenieść je do funkcji `main()`.

7. W `level.py` jest nieprawdziwy docstring.

8. W `window.py` zrobić coś, żeby nie powtarzać *N* razy pętli `for event in pygame.event.get()` — na przykład zrobić z niej metodę, do której przekazujemy listę interesujących prostokątów, a ona zwraca numer klikniętego prostokąta.

9. Używane biblioteki zewnętrzne (czyli `pygame`) wpisać do pliku `requirements.txt` (składnię Pan sobie znajdzie). Dzięki temu użytkownik będzie mógł je zainstalować przez `pip install -r requirements.txt`

**Comment by MarcinCiura** [comment]
Dziękuję za podjęcie działań. Kiedy będzie Pan gotów na kolejną rundę, proszę dać mi znać.

**Comment by PrzemekBarczyk** [comment]
Do końca weekendu majowego postaram się dopracować program pod kątem Pana uwag. Potem będę gotów żeby przejść dalej.

**Comment by PrzemekBarczyk** [comment]
Wprowadziłem wszystkie zmiany z Uwag (#1). Jestem gotów na kolejny etap.

**Comment by MarcinCiura** [comment]
Imponujący projekt. Oprócz pliku `judge.py` i powtarzającego się sprawdzania, który klawisz naciśnięto w `window.py` — LGTM. [Tutaj](https://github.com/przemekbarczyk/arkanoid/blob/27d16c51b9bbc5b1dc14e262790967cb8f481d7b/game_module/window.py#L244) warto zastosować pętlę `for` z `enumerate()`.

**Comment by PrzemekBarczyk** [comment]
Dodałem poprawki na podstawie pliku `README.md` z Pańskiego repozytorium. Napisałem również trochę testów do najważniejszych modułów w programie. Proszę dać mi znać czy ich ilość jest wystarczająca.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany.

1. Testy: przenieść do `game_test.py` (Skąd Pański pomysł na nazwę? Widzę go z siódmy raz.) `TestGame` na `GameTest`. `tearDown()` wyrzucić. Docstringi w testach wyrzucić, bo nie są ani potrzebne, ani zalecane, ani odkrywcze. [Testy mają działać bez interakcji z otoczeniem. Nadto zamiast "na dwoje babka wróżyła" należałoby zrobić dwa osobne testy](https://github.com/przemekbarczyk/arkanoid/blob/01f0ff70ace7b0ccc187f6c6f76a957ef970d0d8/test_game.py#L50). Ale biorąc pod uwagę pierwsze zdanie, najprościej będzie wyrzucić ten test. Liczba testów wystarczy. Dokładnie te same uwagi w `test_ball.py` itd. [To i następne](https://github.com/przemekbarczyk/arkanoid/blob/01f0ff70ace7b0ccc187f6c6f76a957ef970d0d8/game_module/test_racket.py#L33) wyrzucić.
2. [Zamiast komentarzy lepsze nazwane stałe](https://github.com/przemekbarczyk/arkanoid/blob/01f0ff70ace7b0ccc187f6c6f76a957ef970d0d8/game.py#L45) (2. rozdział).
3. [To niedobre](https://github.com/przemekbarczyk/arkanoid/blob/01f0ff70ace7b0ccc187f6c6f76a957ef970d0d8/game_module/constants.py#L4). Zrobić w `constants.py` klasę `Assets`, ew. `Fonts` wg recepty z 3. rozdziału.
4. [Stała](https://github.com/przemekbarczyk/arkanoid/blob/01f0ff70ace7b0ccc187f6c6f76a957ef970d0d8/game_module/judge.py#L20).
5. [`NUM_LIVES`](https://github.com/przemekbarczyk/arkanoid/blob/01f0ff70ace7b0ccc187f6c6f76a957ef970d0d8/game_module/judge.py#L27) (stała; 1 life-3 lives).

**Comment by PrzemekBarczyk** [comment]
Wprowadziłem poprawki na podstawie powyższej listy.

1')  Pomysł na to by moduły i klasy nazywać zaczynając od słowa "test" wziął się z poradnika który oglądałem na temat korzystania z modułu `unittest`. Ponadto w pierwszym przykładzie z dokumentacji klasa jest nazywana w ten sam. Analogicznie jest z nazwą modułu w przykładzie z dokumentacji obrazującym jak uruchamiać testy z linii komend.
3')  Proszę spojrzeć na klasę `Fonts` w module `constants.py`. Nie jestem pewien czy dobrze zrozumiałem sposób w jaki powinna być zaimplementowana.

**Comment by MarcinCiura** [comment]
Dziękuję za zmiany. Już blisko.
ad 1. Dziękuję za wyjaśnienie. Wolę swój (i Googla) sposób, dzięki któremu przy wypisywaniu zawartości katalogu testy są obok testowanych modułów.
ad 3. Lepiej robić zmiany w gałęzi master. [To](https://github.com/przemekbarczyk/arkanoid/blob/536629b0380d7dca6fdbcf9dedb60fa5c86b0e04/game_module/constants.py#L10) niepotrzebne. `pygame.init()` przenieść do `main()`, a inicjalizowanie fontów jest niepotrzebne — `pygame.init()` załatwia wszystko.

**Comment by PrzemekBarczyk** [comment]
Usunąłem inicjalizacje zerami zmiennych z klasy `Fonts` w module `constants.py` oraz inicjalizację fontów. `pygame.init() `przeniosłem do `main()`.
Zmiany z gałęzi `hotfix` zostały wprowadzone na główną gałąź a gałąź `hotfix` usunięta. Dalsze zmiany będą wprowadzane bezpośrednio na gałęzi `master`.

**Comment by MarcinCiura** [comment]
LGTM. Gratuluję, jest Pan dziesiąty.
[Czy to jest potrzebne](https://github.com/przemekbarczyk/arkanoid/blob/1b63cc1b16706c11a01fdaddecc02f15aa1a2044/game_module/racket_test.py#L17)?

**Comment by PrzemekBarczyk** [comment]
Usunąłem zbędne tworzenie obiektu klasy `Game` w metodzie `setUp()` w testach modułów `ball.py` i `racket.py`.
Dodałem kilka nowych testów modułu `window.py`.

Jeśli uzna Pan że dodane testy są w porządku to zabieram się za pisanie raportu.

**Comment by MarcinCiura** [comment]
Dziękuję za wiadomość. Testy są w porządku. Może Pan pisać raport.

**Comment by PrzemekBarczyk** [comment]
Proszę mi jeszcze napisać, czy konieczne jest zawarcie w raporcie linków do wymaganych elementów (lambdy itp.) wymienionych w wytycznych do projektu z elf'a?

**Comment by MarcinCiura** [comment]
Na wszelki wypadek proszę zamieścić w raporcie linki, chyba że nie ma do czego.

Dodatkowa prośba: jeśli nikt tego przed Panem nie zrobi, proszę ogłosić konsultacje w niedzielę o 20:30 i w poniedziałek o 12:00 pod standardowym linkiem. Dziękuję!

**Comment by PrzemekBarczyk** [comment]
Projekt wraz z raportem rozbudowanym o linki został wrzucony na elf'a.
Dziękuje za pomoc z Pana strony i wszystkie cenne uwagi w trakcie realizacji tego zadania.

Informacja o konsultacjach została już ogłoszona przez jednego ze studentów około 10 godzin temu.
